/*
    The controller acts as the connection between the view and the model of this program.
    The controller will... 
    1. The controller recieves input from view class.
    2. The controller then transcribes the input.
    3. The controller now will call the appropriate model method.

       The controller : Controller.Java
       The view class : View.Java
       The model class : Moderator.Java
*/
public class Controller {

    /* User will type into command line when its 
        their turn. A list of words is only accessible.
        Everything else is rejected. Rejected inputs
        are reasked for input.

        --""
        --""
        --""
        --""
    */
    public void setPlayers(String playerString) {
        switch(playerString)

        case playerString == "":
            break;
            
        
        default:        

    }


    public String handleInput(String input) {
        switch(input)

        case input == "":
            break;
            
        case input == "":
            break;

        case input == "":
            break;
        
        case input == "":
            break;

        case input == "":
            break;
        
        default:

    }

}